services:
  - type: web
    name: cricsense-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_app:app
    envVars:
      - key: PORT
        value: 10000
